---
title: "Data Science Applied to Ag - Final Project - ML"
format:
  html:
    embed-resources: true
    toc: true
    theme: cerulean
author: Group 1 (Mari, Oluwatomide)
---
#Loading Library
```{r, warning = False, message = False}
library(tidyverse)
library(randomForest)
library(xgboost)
library(caret)
library(lubridate)
library(readr)
library(dplyr)
library(tidymodels)
library(vip)
library(ranger)
library(finetune)
```



#Viewing Files
```{r}
training_metadata <- read_csv("../data/training/training_meta.csv")

training_soil <- read_csv("../data/training/training_soil.csv")

training_trait <- read_csv("../data/training/training_trait.csv")

testing_submission <- read_csv("../data/testing/testing_submission.csv")

#view(training_metadata)
#view(training_soil)
#view(training_trait)
view(testing_submission)

```


#Removing Duplicates
```{r}

training_soil1 <- training_soil %>%
  select(!(year)) %>%
  separate(site,
                   into = c("site", "year")) %>%
  mutate(year = as.numeric(year)) %>%
  filter(nchar(as.character(year)) == 4)

training_metadata1<- training_metadata %>%
  separate(site, 
                  into = c("site", "x")) %>%
  select(!(x)) %>% #remove x column
  unique()

training_trait1 <- training_trait %>%
  separate(site, 
                  into = c("site", "x")) %>%
  select(!(x)) #remove x column with the -Dry, -Early, -Late

view(training_soil1)
view(training_metadata1)
view(training_trait1)
```



#Creating Merged Dataset
```{r}
training_merged <- training_trait1 %>%
  left_join(training_soil1, by = c("site", "year")) %>%
  left_join(training_metadata1, by = c("site", "year"))

view(training_merged)


```
#Mapping Sites

```{r}
library(USAboundaries)
library(ggplot2)
library(dplyr)
library(sf)
site_locations <- us_states() %>%
filter(!(state_abbr %in% c("PR", "AK", "HI")))
ggplot() +
  geom_sf(data = site_locations) +
  geom_point(data = training_merged, 
             aes(x = longitude,
                 y = latitude,
                color = yield_mg_ha)
  )

#Making a map to identify the site distributions. PR, AK, HI were removed since they did not have sites. Points exist in the Mediterranean between Corsica and Italy, i.e. Site NEH2 (which exists in the final testing_submission file).
```
#Making Sites Only Identical
```{r}
setdiff(testing_submission$site, training_merged$site)  # sites in df1 but not df2
setdiff(training_merged$site, testing_submission$site)  # sites in df2 but not df1
```

```{r}
#Drop sites from training_merged that to not need to be predicted to complete testing_submission. ONH1 and 2 are in proximity to one another, however to not appear in the testing_submission dataframe. ONH3 (a new site) appears in testing_submission. Potential to predict ONH3 based on ONH1 and ONH2, so will not remove them.

training_merged1 <- training_merged %>%
  filter(!(site %in% c("IAH1a" ,"IAH1b" ,"IAH1c", "IAH3" , "MOH2" , "NYH1" ,"TXH2" , "IAH1" , "KSH1" , "NEH4" , "SDH1" , "ARH1" , "ARH2",  "COH1" ,"GEH1",  "TXH3" , "TXH4" , "NYS1" ))) %>%
  mutate(id = row_number(), .before = "year") #adding an ID column at the front of the table to identify rows

write_csv(training_merged1,"../data/training_merged1.csv")

#confirm: 
setdiff(testing_submission$site, training_merged1$site)  # sites in df1 but not df2
setdiff(training_merged1$site, testing_submission$site)  # sites in df2 but not df1

```


#loading Soil DB for Nitrogen ppm
```{r}
#install.packages("soilDB")
#install.packages("aqp")
library("soilDB")
library("aqp")

# Example: get soil data by coordinates
added_nitrogen_values <- fetchSoilGrids(
  training_merged1,
  loc.names = c("id","latitude","longitude"),
  variables = "nitrogen",
  depth_intervals = "0-5"
)
  
#I STOPPED RUNNING BECAUSE IT TOOK A VERY LONG TIME
```


#potential open-source data to add
```{r}
#Weather Data like Growing Degree Days (GDD) from NOAA/PRISM(US)
#can add column like rainfall_30days_post_planting and GDD_silking_period

#STEPS FOR GDD from NOAA/PRISM(US)
#First extract Tmax and Tmin (daily max and min values from specific long and lats)
#Then, calculate GDD from daily temperatures by latitude and longitude 
#GDD = ((Tmax + Tmin)/2) - (Tbase)

#Base Temperature for GDD for Corn is 10C  https://ndawn.ndsu.nodak.edu/help-corn-growing-degree-days.html 

#ALSO LOOK INTO NASA POWER for this data



#Soil Characteristics from SoilGrids by Lat/Long
#can add column like CEC (cation exchange capacity) or soil_texture (i.e. sand/silt/clay%) or bulk_density or water_holding_capacity
```

